version: '3.8'

services:
  sidecar:
    image: nginx:1.26.0-alpine3.19-slim
    container_name: sidecar-nginx
    restart: always
    volumes:
      - /etc/letsencrypt/live/citasdemo.wsbots.com.es/fullchain.pem:/etc/letsencrypt/live/citasdemo.wsbots.com.es/fullchain.pem
      - /etc/letsencrypt/live/citasdemo.wsbots.com.es/privkey.pem:/etc/letsencrypt/live/citasdemo.wsbots.com.es/privkey.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
      - "80:80"
    networks:
      - chatbotinfocitas_network
networks:
  chatbotinfocitas_network:
    external: true
